global:
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
    - PrometheusProto
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText0.0.4
  evaluation_interval: 1m

storage:
  tsdb:
    out_of_order_time_window: 10m
  exemplars:
    max_exemplars: 100000

scrape_configs:
  - job_name: 'burrow'
    static_configs:
      - targets: ['burrow-exporter:8237']