{
 "title": "Kafka Lag",
 "description": "Dashboard for metrics kafka LAG on the Burrow and Burrow Exporter",
 "tags": [
  "stable",
  "kafka"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(kafka_burrow_topic_partition_offset, job)"
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_burrow_partition_lag{job=\"$job\"}, instance)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(kafka_burrow_total_lag{job=\"$job\"}, group)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_burrow_partition_lag{job=\"$job\",group=~\"$group\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Producer Offset",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic, partition) (kafka_burrow_topic_partition_offset{topic=~\"$topic\"})",
     "legendFormat": "{{topic}} / {{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group/topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort(sum by(topic, group) (kafka_burrow_partition_lag{job=\"$job\", instance=~\"$broker\", topic=~\"$topic\", topic!=\"__consumer_offsets\"}))",
     "legendFormat": "Topic: {{topic}} / Group: {{group}}"
    }
   ]
  },
  {
   "title": "Lag Per Partition",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kafka_burrow_partition_lag{job=\"$job\",instance=~\"$broker\",topic=~\"$topic\",topic!=\"__consumer_offsets\"}"
    }
   ]
  }
 ]
}